# Generated by Django 5.1.1 on 2024-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='photo/')),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderImg',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
