# Generated by Django 5.1.1 on 2024-10-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_upload',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.catagory'),
        ),
    ]
