# Generated by Django 5.1.1 on 2024-10-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_backgroundimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundImg',
            new_name='BackImg',
        ),
    ]
