# Generated by Django 5.1.1 on 2024-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_backgroundimg_backimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backimg',
            name='picture',
            field=models.ImageField(upload_to='Back/'),
        ),
    ]
