# Generated by Django 5.1.1 on 2024-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_backimg_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackImg',
        ),
    ]
