# Generated by Django 5.1.1 on 2024-10-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_rename_image_frontimg_imageorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontimg',
            name='imageOrg',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
