# Generated by Django 5.1.1 on 2024-10-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_frontimg_imageorg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('length', models.FloatField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
                ('profileOwner', models.CharField(max_length=30)),
                ('profileImg', models.ImageField(upload_to='')),
                ('profilePhone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FrontImg',
        ),
        migrations.DeleteModel(
            name='Main_upload',
        ),
    ]
