# Generated by Django 5.1.1 on 2024-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_uploadcontainer_delete_frontimg_delete_main_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcontainer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
