# Generated by Django 5.1.1 on 2024-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_uploadcontainer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='BackgroundImg')),
            ],
        ),
    ]
